export type Pagina =
  | 'inicio'
  | 'catalogo'
  | 'registro'
  | 'entrar'
  | 'tablero'
  | 'verificacion'
  | 'cola'
  | 'animal'
  | 'entidadPub'
  | 'alta'
  | 'postulaciones'
  | 'cuestionario'
  | 'deseos'
  | 'necesidades'
  | 'misPostulaciones';
